name: Deploy to production

on: 
  push:
    branches: 
      - prod
      - stage

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: say Yay
        run: |
          echo Deploy to PROD. Yay!
